GET http://localhost:3001/api/persons/62fe85f5e9a046675b2e2016

###

DELETE http://localhost:3001/api/persons/3

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"Matti Luukkainen",
    "number":"040-123456"
}