GET http://localhost:3001/api/persons/4

###

DELETE http://localhost:3001/api/persons/4

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"Matti Luukkainen",
    "number":"040-123456"
}